[package]
name = "code-library-backend"
version = "0.1.0"
authors = ["Markus Merklinger <markus.merklinger@code.berlin>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "identity"
path = "src/identity/main.rs"

[[bin]]
name = "book"
path = "src/book/main.rs"

[[bin]]
name = "loan"
path = "src/loan/main.rs"

[[bin]]
name = "message"
path = "src/message/main.rs"

[[bin]]
name = "api"
path = "src/api/main.rs"

[dependencies]
